//! Multi-Page Co-Pagination Engine with Automatic Overflow Splitting.
//!
//! Orchestrates coordinated page generation across parallel text streams (Gemara, Rashi, Tosafot):
//! - Tracks anchor dependencies between central text and commentaries.
//! - Detects commentary overflow or excessive lag on the current page.
//! - Automatically cuts central text at the optimal anchor boundary and pushes
//!   remaining central text and dependent commentaries to subsequent pages.
//! - Dynamically synthesizes L-shapes under early-terminating central text.
//! - Applies active vertical springs to align commentary headings with anchors.

use super::sync::{
    ActiveSyncResult, ActiveSynchronizer, AnchorKey, SyncRemedy, SynchronizerConfig,
};
use super::template::{SpreadMathematics, TemplateConfig};
use crate::engine::TypesettingEngine;
use crate::geometry::{LineBox, PageLayoutBox, PhysicalRect, TextFrameBox};
use std::collections::{HashMap, VecDeque};
use tok_core::id::FractionalIndex;
use tok_core::model::ParagraphNode;

/// A central text paragraph (Gemara) containing one or more anchor phrases.
#[derive(Debug, Clone)]
pub struct CoPaginatedChunk {
    pub text: String,
    /// (anchor_key, exact search phrase in `text`)
    pub anchors: Vec<(AnchorKey, String)>,
}

/// A commentary paragraph (Rashi or Tosafot) attached to a specific central anchor.
#[derive(Debug, Clone)]
pub struct CoPaginatedCommentary {
    pub target_anchor: AnchorKey,
    pub text: String,
}

/// A complete multi-stream document input for co-pagination.
#[derive(Debug, Clone, Default)]
pub struct CoPaginationDocument {
    pub main_chunks: Vec<CoPaginatedChunk>,
    pub rashi_items: Vec<CoPaginatedCommentary>,
    pub tosafot_items: Vec<CoPaginatedCommentary>,
}

/// Layout details for a single page generated by the co-pagination engine.
#[derive(Debug, Clone)]
pub struct CoPaginatedPage {
    pub page_number: usize,
    pub page_layout: PageLayoutBox,
    pub math: SpreadMathematics,
    pub gemara_lines_count: usize,
    pub rashi_lines_count: usize,
    pub tosafot_lines_count: usize,
    pub rashi_expanded_lines_count: usize,
    pub sync_results: Vec<ActiveSyncResult>,
}

/// Result of multi-page co-pagination across the entire document.
#[derive(Debug, Clone)]
pub struct CoPaginationResult {
    pub pages: Vec<CoPaginatedPage>,
    pub total_pages: usize,
    pub total_gemara_lines: usize,
    pub total_rashi_lines: usize,
    pub total_tosafot_lines: usize,
    pub all_anchors_remedied: bool,
}

pub struct CoPaginationEngine;

impl CoPaginationEngine {
    pub const MAX_PAGES_SAFETY: usize = 500;

    /// Co-paginates an entire multi-stream document across consecutive book pages,
    /// automatically splitting central text when commentary overflows and carrying over
    /// remaining content to subsequent pages.
    pub fn co_paginate(
        config: &TemplateConfig,
        sync_config: &SynchronizerConfig,
        doc: &CoPaginationDocument,
        engine: &TypesettingEngine,
    ) -> CoPaginationResult {
        let mut remaining_chunks: VecDeque<CoPaginatedChunk> =
            doc.main_chunks.iter().cloned().collect();
        let mut remaining_rashi: VecDeque<CoPaginatedCommentary> =
            doc.rashi_items.iter().cloned().collect();
        let mut remaining_tosafot: VecDeque<CoPaginatedCommentary> =
            doc.tosafot_items.iter().cloned().collect();

        let mut pages = Vec::new();
        let mut total_gemara_lines = 0;
        let mut total_rashi_lines = 0;
        let mut total_tosafot_lines = 0;
        let mut all_anchors_remedied = true;

        let mut page_number = 1;

        while (!remaining_chunks.is_empty()
            || !remaining_rashi.is_empty()
            || !remaining_tosafot.is_empty())
            && page_number <= Self::MAX_PAGES_SAFETY
        {
            let math = SpreadMathematics::for_page(config, page_number);

            let max_gemara_lines =
                (math.content_height_pt / config.main_line_height).floor() as usize;
            let max_commentary_lines =
                (math.content_height_pt / config.commentary_line_height).floor() as usize;

            // 1. Greedily determine which Gemara chunks fit on this page without overflowing commentary
            let mut page_chunks = Vec::new();
            let mut tentative_gemara_lines: Vec<LineBox> = Vec::new();
            let mut tentative_gemara_anchors: HashMap<AnchorKey, (usize, f32)> = HashMap::new();
            let mut current_g_y = 0.0;

            // Rough commentary demand accumulator (characters)
            let mut page_rashi_chars = 0;
            let mut page_tosafot_chars = 0;
            let max_rashi_chars_approx = max_commentary_lines * 45;
            let max_tosafot_chars_approx = max_commentary_lines * 50;

            while let Some(chunk) = remaining_chunks.pop_front() {
                let p_node = ParagraphNode::new(
                    FractionalIndex::new(format!("g_{}_{}", page_number, page_chunks.len())),
                    "gemara",
                    &chunk.text,
                );
                let main_profile = math.create_measure_profile(config, "main", None);
                let chunk_lines = engine.typeset_paragraph_shaped(
                    &p_node,
                    &config.main_font_family,
                    &main_profile,
                    config.main_font_size,
                    config.main_line_height,
                );

                if !tentative_gemara_lines.is_empty()
                    && tentative_gemara_lines.len() + chunk_lines.len() > max_gemara_lines
                {
                    // Gemara itself overflows: push chunk back and finish page
                    remaining_chunks.push_front(chunk);
                    break;
                }

                // Check commentary demand for this chunk's anchors
                let mut chunk_rashi_demand = 0;
                let mut chunk_tosafot_demand = 0;
                for (a_key, _) in &chunk.anchors {
                    for r in remaining_rashi.iter().filter(|r| r.target_anchor == *a_key) {
                        chunk_rashi_demand += r.text.len();
                    }
                    for t in remaining_tosafot
                        .iter()
                        .filter(|t| t.target_anchor == *a_key)
                    {
                        chunk_tosafot_demand += t.text.len();
                    }
                }

                // If adding this chunk causes unbridgeable commentary overflow, split and push to next page
                if !page_chunks.is_empty()
                    && (page_rashi_chars + chunk_rashi_demand > max_rashi_chars_approx
                        || page_tosafot_chars + chunk_tosafot_demand > max_tosafot_chars_approx)
                {
                    remaining_chunks.push_front(chunk);
                    break;
                }

                // Record anchor positions within chunk
                for (a_key, phrase) in &chunk.anchors {
                    let mut anchor_line_rel = 0;
                    for (l_idx, line) in chunk_lines.iter().enumerate() {
                        if line.text.contains(phrase) {
                            anchor_line_rel = l_idx;
                            break;
                        }
                    }
                    let abs_l = tentative_gemara_lines.len() + anchor_line_rel;
                    let abs_y =
                        current_g_y + (anchor_line_rel as f32 + 1.0) * config.main_line_height;
                    tentative_gemara_anchors.insert(a_key.clone(), (abs_l, abs_y));
                }

                current_g_y += chunk_lines.len() as f32 * config.main_line_height;
                tentative_gemara_lines.extend(chunk_lines);
                page_rashi_chars += chunk_rashi_demand;
                page_tosafot_chars += chunk_tosafot_demand;
                page_chunks.push(chunk);

                // Stop adding if Gemara is at or near full column
                if tentative_gemara_lines.len() >= max_gemara_lines {
                    break;
                }
            }

            // Gemara height on this page
            let gemara_h = tentative_gemara_lines.len() as f32 * config.main_line_height;

            // 2. Synthesize dynamic L-shape profile for Rashi on this page
            let rashi_profile = math.create_measure_profile(config, "rashi", Some(gemara_h));
            let tosafot_profile = math.create_measure_profile(config, "tosafot", None);

            let rashi_narrow_lines = (gemara_h / config.commentary_line_height).ceil() as usize;

            // 3. Typeset Rashi for anchors assigned to this page, plus any carry-overs
            let mut page_rashi_lines: Vec<LineBox> = Vec::new();
            let mut rashi_anchor_positions: HashMap<AnchorKey, f32> = HashMap::new();
            let mut rashi_line_counter = 0;
            let mut sync_results = Vec::new();

            // Collect Rashi items matching this page's anchors
            let mut this_page_rashi = Vec::new();
            let mut unplaced_rashi = VecDeque::new();

            while let Some(item) = remaining_rashi.pop_front() {
                if tentative_gemara_anchors.contains_key(&item.target_anchor)
                    || (page_chunks.is_empty() && this_page_rashi.len() < max_commentary_lines)
                {
                    this_page_rashi.push(item);
                } else {
                    unplaced_rashi.push_back(item);
                }
            }
            remaining_rashi = unplaced_rashi;

            // Typeset each Rashi paragraph with profile & active synchronization
            for (p_idx, item) in this_page_rashi.into_iter().enumerate() {
                let start_line = rashi_line_counter;
                let natural_y = start_line as f32 * config.commentary_line_height;

                // Create paragraph-offset profile
                let p_profile = if !rashi_profile.is_uniform() {
                    if start_line < rashi_narrow_lines {
                        let remaining_narrow = rashi_narrow_lines - start_line;
                        let exp_w =
                            math.inner_column_width_pt + math.main_column_width_pt + math.gutter_pt;
                        crate::knuth_plass::MeasureProfile::l_shape(
                            remaining_narrow,
                            math.inner_column_width_pt,
                            exp_w,
                        )
                    } else {
                        let exp_w =
                            math.inner_column_width_pt + math.main_column_width_pt + math.gutter_pt;
                        crate::knuth_plass::MeasureProfile::uniform(exp_w)
                    }
                } else {
                    crate::knuth_plass::MeasureProfile::uniform(math.inner_column_width_pt)
                };

                let p_node = ParagraphNode::new(
                    FractionalIndex::new(format!("r_{}_{}", page_number, p_idx)),
                    "rashi",
                    &item.text,
                );
                let mut p_lines = engine.typeset_paragraph_shaped(
                    &p_node,
                    &config.commentary_font_family,
                    &p_profile,
                    config.commentary_font_size,
                    config.commentary_line_height,
                );

                if rashi_line_counter + p_lines.len() > max_commentary_lines + 2
                    && !page_rashi_lines.is_empty()
                {
                    // Commentary overflows: push this item back to remaining for next page
                    remaining_rashi.push_front(item);
                    break;
                }

                // Evaluate active synchronization
                let mut spring_pt = 0.0;
                if let Some(&(_, g_y)) = tentative_gemara_anchors.get(&item.target_anchor) {
                    let sync = ActiveSynchronizer::evaluate_and_remedy(
                        sync_config,
                        &item.target_anchor,
                        g_y,
                        "rashi",
                        natural_y,
                    );
                    if let SyncRemedy::VerticalSpringApplied { spring_pt: s } = sync.remedy {
                        spring_pt = s;
                        ActiveSynchronizer::apply_spring_offset(&mut p_lines, spring_pt);
                    }
                    if matches!(
                        sync.remedy,
                        SyncRemedy::ExcessiveLead { .. } | SyncRemedy::RequirePageCut { .. }
                    ) {
                        all_anchors_remedied = false;
                    }
                    sync_results.push(sync);
                }

                rashi_anchor_positions.insert(item.target_anchor.clone(), natural_y + spring_pt);
                rashi_line_counter += p_lines.len();
                page_rashi_lines.extend(p_lines);
            }

            // 4. Typeset Tosafot for this page
            let mut page_tosafot_lines: Vec<LineBox> = Vec::new();
            let mut tosafot_line_counter = 0;
            let mut this_page_tosafot = Vec::new();
            let mut unplaced_tosafot = VecDeque::new();

            while let Some(item) = remaining_tosafot.pop_front() {
                if tentative_gemara_anchors.contains_key(&item.target_anchor)
                    || (page_chunks.is_empty() && this_page_tosafot.len() < max_commentary_lines)
                {
                    this_page_tosafot.push(item);
                } else {
                    unplaced_tosafot.push_back(item);
                }
            }
            remaining_tosafot = unplaced_tosafot;

            for (p_idx, item) in this_page_tosafot.into_iter().enumerate() {
                let start_line = tosafot_line_counter;
                let natural_y = start_line as f32 * config.commentary_line_height;

                let p_node = ParagraphNode::new(
                    FractionalIndex::new(format!("t_{}_{}", page_number, p_idx)),
                    "tosafot",
                    &item.text,
                );
                let mut p_lines = engine.typeset_paragraph_shaped(
                    &p_node,
                    &config.commentary_font_family,
                    &tosafot_profile,
                    config.commentary_font_size,
                    config.commentary_line_height,
                );

                if tosafot_line_counter + p_lines.len() > max_commentary_lines + 2
                    && !page_tosafot_lines.is_empty()
                {
                    remaining_tosafot.push_front(item);
                    break;
                }

                if let Some(&(_, g_y)) = tentative_gemara_anchors.get(&item.target_anchor) {
                    let sync = ActiveSynchronizer::evaluate_and_remedy(
                        sync_config,
                        &item.target_anchor,
                        g_y,
                        "tosafot",
                        natural_y,
                    );
                    if let SyncRemedy::VerticalSpringApplied { spring_pt } = sync.remedy {
                        ActiveSynchronizer::apply_spring_offset(&mut p_lines, spring_pt);
                    }
                    sync_results.push(sync);
                }

                tosafot_line_counter += p_lines.len();
                page_tosafot_lines.extend(p_lines);
            }

            // Count expanded lines in Rashi
            let rashi_expanded_count = page_rashi_lines
                .iter()
                .enumerate()
                .filter(|(idx, line)| {
                    *idx >= rashi_narrow_lines || line.width > math.inner_column_width_pt + 1.0
                })
                .count();

            // 5. Build physical page frames matching SpreadMathematics
            let mut frames = Vec::new();
            for col in &math.columns {
                let lines = match col.stream_id.as_str() {
                    "main" => tentative_gemara_lines.clone(),
                    "rashi" => page_rashi_lines.clone(),
                    "tosafot" => page_tosafot_lines.clone(),
                    _ => Vec::new(),
                };

                frames.push(TextFrameBox {
                    frame_id: format!("frame_{}_{}", page_number, col.stream_id),
                    flow_id: col.stream_id.clone(),
                    rect: PhysicalRect::new(col.x_pt, col.y_pt, col.width_pt, col.max_height_pt),
                    lines,
                });
            }

            let page_layout = PageLayoutBox {
                page_index: page_number - 1,
                page_number_gematria: crate::gematria::GematriaEngine::to_hebrew_numeral(
                    page_number,
                ),
                dimensions: PhysicalRect::new(
                    0.0,
                    0.0,
                    config.page_width_pt,
                    config.page_height_pt,
                ),
                frames,
                break_token: None,
            };

            total_gemara_lines += tentative_gemara_lines.len();
            total_rashi_lines += page_rashi_lines.len();
            total_tosafot_lines += page_tosafot_lines.len();

            pages.push(CoPaginatedPage {
                page_number,
                page_layout,
                math,
                gemara_lines_count: tentative_gemara_lines.len(),
                rashi_lines_count: page_rashi_lines.len(),
                tosafot_lines_count: page_tosafot_lines.len(),
                rashi_expanded_lines_count: rashi_expanded_count,
                sync_results,
            });

            page_number += 1;
        }

        CoPaginationResult {
            total_pages: pages.len(),
            pages,
            total_gemara_lines,
            total_rashi_lines,
            total_tosafot_lines,
            all_anchors_remedied,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::TypesettingEngineConfig;

    fn test_engine() -> TypesettingEngine {
        TypesettingEngine::new(TypesettingEngineConfig::default())
    }

    #[test]
    fn test_co_pagination_multi_page_splitting_and_carry_over() {
        let engine = test_engine();
        let config = TemplateConfig::default();
        let sync_config = SynchronizerConfig::default();

        // Document with 3 chunks of Gemara and ample commentaries
        let doc = CoPaginationDocument {
            main_chunks: vec![
                CoPaginatedChunk {
                    text: "מאימתי קורין את שמע בערבין משעה שהכהנים נכנסים לאכול בתרומתן עד סוף האשמורה הראשונה דברי רבי אליעזר וחכמים אומרים עד חצות רבן גמליאל אומר עד שיעלה עמוד השחר".to_string(),
                    anchors: vec![
                        (AnchorKey::new("dh_1"), "מאימתי".to_string()),
                        (AnchorKey::new("dh_2"), "עד חצות".to_string()),
                    ],
                },
                CoPaginatedChunk {
                    text: "תנא היכא קאי דקתני מאימתי ותו מאי שנא דתני בערבית ברישא לתני דשחרית ברישא תנא אקרא קאי דכתיב בשכבך ובקומך".to_string(),
                    anchors: vec![(AnchorKey::new("dh_3"), "תנא היכא קאי".to_string())],
                },
                CoPaginatedChunk {
                    text: "אמר מר משעה שהכהנים נכנסים לאכול בתרומתן ורמינהו עד צאת הכוכבים ומשני לא קשיא הא ברמשא והא בצפרא".to_string(),
                    anchors: vec![(AnchorKey::new("dh_4"), "אמר מר".to_string())],
                },
            ],
            rashi_items: vec![
                CoPaginatedCommentary {
                    target_anchor: AnchorKey::new("dh_1"),
                    text: "מאימתי קורין וכו' - לא קאי אקרא אלא אמשנה דלעיל דתנן תפלת השחר עד חצות".to_string(),
                },
                CoPaginatedCommentary {
                    target_anchor: AnchorKey::new("dh_2"),
                    text: "עד חצות - כדי להרחיק את האדם מן העבירה שלא יאמר אדם יש לי עוד שהות".to_string(),
                },
                CoPaginatedCommentary {
                    target_anchor: AnchorKey::new("dh_3"),
                    text: "תנא היכא קאי - מאיזה מקום למד דין זה שהתחיל לשאול מאימתי קורין".to_string(),
                },
                CoPaginatedCommentary {
                    target_anchor: AnchorKey::new("dh_4"),
                    text: "אמר מר - ביאור על הברייתא המובאת בגמרא בעניין צאת הכוכבים".to_string(),
                },
            ],
            tosafot_items: vec![
                CoPaginatedCommentary {
                    target_anchor: AnchorKey::new("dh_1"),
                    text: "מאימתי קורין את שמע בערבין - תימא דבכל מקום מקדים תפלת שחרית לתפלת ערבית".to_string(),
                },
                CoPaginatedCommentary {
                    target_anchor: AnchorKey::new("dh_3"),
                    text: "תנא היכא קאי - אור\"י דקאי אקרא דבשכבך ובקומך".to_string(),
                },
            ],
        };

        let result = CoPaginationEngine::co_paginate(&config, &sync_config, &doc, &engine);

        assert!(
            result.total_pages >= 1,
            "Expected at least 1 page generated"
        );
        assert!(result.total_gemara_lines > 0);
        assert!(result.total_rashi_lines > 0);
        assert!(result.total_tosafot_lines > 0);

        // Page 1 must have valid frames
        let page1 = &result.pages[0];
        assert_eq!(page1.page_number, 1);
        assert_eq!(page1.math.side, crate::multi_flow::SpreadSide::Recto);
        assert_eq!(page1.page_layout.frames.len(), 3); // rashi, main, tosafot
    }

    #[test]
    fn test_co_pagination_pushes_overflowing_content_to_next_page() {
        let engine = test_engine();
        let config = TemplateConfig::default();
        let sync_config = SynchronizerConfig::default();

        // Many Gemara chunks that exceed a single page's capacity
        let mut chunks = Vec::new();
        let mut rashi = Vec::new();
        for i in 0..28 {
            let key = AnchorKey::new(format!("anchor_{}", i));
            chunks.push(CoPaginatedChunk {
                text: format!("קטע גמרא מספר {} העוסק בדיני קריאת שמע והזמנים השונים של התפילה עם מילים נוספות להארכה", i),
                anchors: vec![(key.clone(), format!("מספר {}", i))],
            });
            rashi.push(CoPaginatedCommentary {
                target_anchor: key,
                text: format!("פירוש רש\"י מפורט עבור קטע מספר {} שממחיש את שבירת העמודים והמעבר הרציף בין עמודים", i),
            });
        }

        let doc = CoPaginationDocument {
            main_chunks: chunks,
            rashi_items: rashi,
            tosafot_items: Vec::new(),
        };

        let result = CoPaginationEngine::co_paginate(&config, &sync_config, &doc, &engine);

        // Content exceeds one page; must generate multiple pages cleanly
        assert!(
            result.total_pages >= 2,
            "Expected multiple pages due to overflow, got {}",
            result.total_pages
        );
        assert_eq!(result.pages[0].page_number, 1);
        assert_eq!(result.pages[1].page_number, 2);

        // Facing spreads alternate Recto -> Verso
        assert_eq!(
            result.pages[0].math.side,
            crate::multi_flow::SpreadSide::Recto
        );
        assert_eq!(
            result.pages[1].math.side,
            crate::multi_flow::SpreadSide::Verso
        );
    }
}
